//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparta_WPF_CRUD_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public string City { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> SpartanID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Spartan Spartan { get; set; }
    }
}
