//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparta_WPF_CRUD_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spartan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spartan()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int SpartanID { get; set; }
        public string SpartanName { get; set; }
        public string Course { get; set; }
        public Nullable<bool> IsPlaced { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
